@startuml

participant "Приложение" as App
participant "Файловая система" as FS

User -> App: Запуск записи на диск
App -> FS: Проверка свободного места на диске
FS -> FS: Проверка свободного места
FS --> App: Свободного места не хватает
App --> User: Ошибка - Недостаточно места на диске
@enduml