@startuml

participant Пользователь
participant Диск
participant Запись

Пользователь --> Запись: Запись данных
Запись --> Диск: Запись данных
Диск --> Диск: Повреждение данных
Диск--> Запись: Ошибка
Запись --> Пользователь: Сообщение об ошибке

@enduml