@startuml

participant Программа
participant Диск
participant Запись

Программа->Диск: Проверка свободного места на диске
Диск-->Программа: Информация о свободном месте на диске

Программа->Запись: Начало записи на диск
Запись->Диск: Попытка записи
Диск-->Запись: Ошибка - недостаточное свободное место на диске
Запись->Диск: Финализация записи
Диск-->Запись: Успешная финализация записи
Запись->Диск: Повторная попытка записи
Диск-->Запись: Успешное выполнение записи

@enduml
