@startuml

participant User
participant "Запись на диск"
participant "Верификация"

User -> "Запись на диск" : Запрос на запись
"Запись на диск" -> "Запись на диск" : Выполнение записи на диск
"Запись на диск" -> "Верификация" : Передача данных для верификации
"Верификация" -> "Верификация" : Выполнение верификации
"Верификация" --> User : Результат верификации: наличие ошибок

@enduml